version: '3'
services:
    mongo:
        image: mongo:jammy
        restart: always
        command: mongod --port 27018
        ports:
            - '27018:27018'
        volumes:
            - mongo-data:/data/db
volumes:
    mongo-data:
        driver: local
